Feature/17464 admin hinzufügen und löschen
BROCKHAUS-AG/DiversityLunch pull request #20
Opened 2022-10-17 06:47 UTC by LucasKarle

2022-10-17 07:12 UTC, Gohlisch requested changes

2022-10-17 07:12 UTC, Gohlisch commented on diversity-lunch-fe/src/components/AdminPanel/user-list.tsx
> +                        {dynamicSearch()}
kein Funktionsaufruf. Lieber vorher in const ablegen und hier einfach herein geben

2022-10-17 07:12 UTC, Gohlisch commented on diversity-lunch-fe/src/components/AdminPanel/OptionsList.tsx
> +        console.log(state.items);
kein console.log

2022-10-17 07:12 UTC, Gohlisch commented on diversity-lunch-fe/src/components/AdminPanel/OptionsList.tsx
> +            id: 21,
warum hier feste id?

2022-10-17 07:12 UTC, Gohlisch commented on diversity-lunch-fe/src/data/accounts/accounts-fetch.ts
> +// TODO: Assign Admin
Noch relevant?

2022-10-17 07:12 UTC, Gohlisch commented on diversity-lunch-fe/src/data/profiles/profiles-fetch.ts
> +// TODO: Assign Admin
Noch relevant?

2022-10-18 16:04 UTC, LucasKarle commented on diversity-lunch-fe/src/data/profiles/profiles-fetch.ts
> +// TODO: Assign Admin
nein

2022-10-25 10:01 UTC, Gohlisch approved these changes

2022-10-25 10:01 UTC, merged