Fix/17791 anlegen von mehreren accounts möglich
BROCKHAUS-AG/DiversityLunch pull request #27
Opened 2022-11-04 09:15 UTC by Gohlisch

2022-11-08 13:01 UTC, N0tAScooby requested changes

2022-11-09 13:13 UTC, N0tAScooby requested changes

2022-11-09 13:13 UTC, N0tAScooby commented on diversity-lunch-fe/src/hooks/authentication/get-userInfo.hook.ts
> +                email: oid,
Wieso steht neben Email: oid. Hier kann was nicht stimmen. Die Email im Profile sollte dennoch eine Email haben und keine Oid

2022-11-09 13:15 UTC, N0tAScooby commented
@Gohlisch Mir ist aufgefallen, dass in der Datenbank Tablle unter Profile statt der Email jetzt die OID steht. Im Profil brauchen wir aber noch die Mail, um Emails verschicken zu können? Beziehungsweise anders gefragt, sollte geschaut werden, dass nach diesen Änderungen der Email Versand noch funktioniert und wir nicht versuchen die OID als Email Addresse zu nehmen.

2022-11-10 08:59 UTC, Gohlisch commented on diversity-lunch-be/src/main/java/de/brockhausag/diversitylunchspringboot/account/service/AccountService.java
>          AccountRole role = determineRole();
funktioniert (bestimmt) mit Azure Admins. Muss man testen.

2022-11-10 09:53 UTC, N0tAScooby approved these changes

2022-11-10 13:29 UTC, merged