Feature/17584 email button admin panel
BROCKHAUS-AG/DiversityLunch pull request #28
Opened 2022-11-08 11:08 UTC by LucasKarle

Added Send Testmail Button to Adminpanel and Cherrypicked PopUp(credit: Fabio;Cornelius)

2022-11-08 12:43 UTC, N0tAScooby requested changes

2022-11-08 12:43 UTC, N0tAScooby commented on diversity-lunch-be/src/main/java/de/brockhausag/diversitylunchspringboot/email/controller/EMailController.java
>              System.out.println("Beginning of try block of sendTestMailToUser");
remove

2022-11-08 12:43 UTC, N0tAScooby commented on diversity-lunch-be/src/main/java/de/brockhausag/diversitylunchspringboot/email/service/DiversityLunchEMailService.java
>          }
Zeile 36 und 38 in diesem File System Out entfernen und durch logging ersetzen

2022-11-08 12:44 UTC, N0tAScooby commented
@LucasKarle Wieso ist der Button zum verschicken so breit?

2022-11-10 07:06 UTC, LucasKarle commented
> @LucasKarle Wieso ist der Button zum verschicken so breit?

iat jetzt hübsch

2022-11-10 07:17 UTC, N0tAScooby approved these changes

2022-11-10 07:17 UTC, merged